[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  VITE_APP_URL = "https://seo.semdash.com"

[[redirects]]
  from = "/api/stripe-webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200
  force = true
  methods = ["POST"]
  headers = {Stripe-Signature = ":stripe-signature"}
